export type Status = "Draft"|"Sent"|"Paid"|"Partially Paid"|"Pending"|"Overdue"|"Cancelled";
export type Client={id:string;name:string;company:string;email:string;phone:string;address:string;gstin:string;pan:string;notes:string;sample?:boolean};
export type Service={id:string;name:string;description:string;rate:number;unit:string;gst:number;active:boolean;sample?:boolean};
export type Item={id:string;description:string;quantity:number;unit:string;rate:number;discount:number;tax:number};
export type Payment={id:string;date:string;amount:number;method:string;reference:string;notes:string};
export type Invoice={id:string;number:string;clientId?:string;client:Client;date:string;dueDate:string;terms:string;status:Status;items:Item[];overallDiscount:number;taxMode:"none"|"intra"|"inter";notes:string;payments:Payment[];createdAt:string;sample?:boolean};
export type Business={name:string;website:string;email:string;phone:string;upiId:string;bank:string;accountName:string;accountNumber:string;ifsc:string;branch:string;gstin:string;pan:string;address:string;terms:string;prefix:string;gst:number;notes:string};
export type AppData={business:Business;clients:Client[];services:Service[];invoices:Invoice[];setup:boolean};
export const uid=()=>crypto.randomUUID();
export const today=()=>new Date().toISOString().slice(0,10);
export const addDays=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
export const fmt=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number.isFinite(n)?n:0);
export function totals(i:Invoice){const subtotal=i.items.reduce((s,x)=>s+x.quantity*x.rate,0);const lineDiscount=i.items.reduce((s,x)=>s+x.quantity*x.rate*x.discount/100,0);const taxable=Math.max(0,subtotal-lineDiscount-i.overallDiscount);const tax=i.taxMode==="none"?0:i.items.reduce((s,x)=>s+(x.quantity*x.rate*(1-x.discount/100))*x.tax/100,0);const paid=i.payments.reduce((s,p)=>s+p.amount,0);return{subtotal,lineDiscount,taxable,tax,grand:Math.round((taxable+tax)*100)/100,paid,outstanding:Math.max(0,Math.round((taxable+tax-paid)*100)/100)}}
export function effectiveStatus(i:Invoice):Status{const t=totals(i);if(i.status==="Cancelled"||i.status==="Draft")return i.status;if(t.outstanding<=.009)return"Paid";if(t.paid>0)return"Partially Paid";if(i.dueDate<today())return"Overdue";return i.status==="Sent"?"Pending":i.status}
export function words(amount:number){const ones=["","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"];const tens=["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"];const under=(n:number):string=>n<20?ones[n]:tens[Math.floor(n/10)]+(n%10?" "+ones[n%10]:"");const part=(n:number,label:string)=>n?under(n)+(label?" "+label+" ":" "):"";const r=Math.round(amount*100);const rupees=Math.floor(r/100),paise=r%100;const crore=Math.floor(rupees/10000000),lakh=Math.floor(rupees%10000000/100000),thousand=Math.floor(rupees%100000/1000),hundred=Math.floor(rupees%1000/100),rest=rupees%100;const text=part(crore,"Crore")+part(lakh,"Lakh")+part(thousand,"Thousand")+part(hundred,"Hundred")+(hundred&&rest?"and ":"")+under(rest);return `${text||"Zero"} Rupees${paise?" and "+under(paise)+" Paise":""} Only`;}
export const blankClient=():Client=>({id:uid(),name:"",company:"",email:"",phone:"",address:"",gstin:"",pan:"",notes:""});
export const blankItem=():Item=>({id:uid(),description:"",quantity:1,unit:"Project",rate:0,discount:0,tax:0});
export const blankInvoice=(b:Business,n:string):Invoice=>({id:uid(),number:n,client:blankClient(),date:today(),dueDate:addDays(15),terms:b.terms,status:"Draft",items:[blankItem()],overallDiscount:0,taxMode:"none",notes:b.notes,payments:[],createdAt:new Date().toISOString()});
export const defaults=():AppData=>({setup:false,business:{name:"Apexmedias",website:"apexmedias.in",email:"apexmedias.in@gmail.com",phone:"8073644604",upiId:"",bank:"State Bank of India (SBI)",accountName:"",accountNumber:"",ifsc:"",branch:"",gstin:"",pan:"",address:"",terms:"Payment due within 15 days.",prefix:"APX",gst:18,notes:"Thank you for choosing Apexmedias."},clients:[],services:[],invoices:[]});
export const nextNumber=(d:AppData)=>{const fy=new Date().getFullYear().toString().slice(-2)+"-"+(new Date().getFullYear()+1).toString().slice(-2);return `${d.business.prefix}/${fy}/${String(d.invoices.length+1).padStart(3,"0")}`};
export const sample=(d:AppData):AppData=>{const clients=[{...blankClient(),id:"c1",name:"Rohan Mehta",company:"Northstar Foods",email:"rohan@northstar.example",phone:"9876543210",address:"Bengaluru, Karnataka",sample:true},{...blankClient(),id:"c2",name:"Ananya Shah",company:"Mitra Home Studio",email:"ananya@mitra.example",phone:"9988776655",address:"Mumbai, Maharashtra",sample:true}];const names=[["Social Media Management",8000,"Month"],["Reel Production",1500,"Reel"],["Video Editing",2500,"Video"],["Graphic Design",1200,"Design"],["Website Development",35000,"Project"],["Photography",6000,"Session"]] as const;const services=names.map(([name,rate,unit],x)=>({id:"s"+x,name,description:"Starter service — edit anytime",rate,unit,gst:18,active:true,sample:true}));const inv=(id:string,number:string,c:Client,items:Item[],status:Status):Invoice=>({id,number,clientId:c.id,client:c,date:"2026-08-"+(id==="i1"?"08":"18"),dueDate:"2026-08-30",terms:d.business.terms,status,items,overallDiscount:0,taxMode:"intra",notes:d.business.notes,payments:status==="Paid"?[{id:uid(),date:"2026-08-10",amount:9440,method:"UPI",reference:"SAMPLE",notes:""}]:[],createdAt:new Date().toISOString(),sample:true});return{...d,clients,services,invoices:[inv("i1","APX/26-27/001",clients[0],[{...blankItem(),description:"Social Media Management",quantity:1,unit:"Month",rate:8000,tax:18}],"Paid"),inv("i2","APX/26-27/002",clients[1],[{...blankItem(),description:"Reel Production",quantity:3,unit:"Reel",rate:1500,tax:18}],"Pending")]};};
